CREATE TABLE orders (
  id            BIGINT AUTO_INCREMENT PRIMARY KEY,
  student_id    BIGINT NOT NULL,
  writer_id     BIGINT,
  college_id    BIGINT,
  order_type    ENUM('RECORD_NOTE','OBSERVATION','ASSIGNMENT','MINI_PROJECT',
                     'FINAL_YEAR_PROJECT','DIAGRAM','LAB_MANUAL','MODEL') NOT NULL,
  description   TEXT,
  deadline      DATETIME,
  pages         INT DEFAULT 1,
  urgency       ENUM('NORMAL','URGENT','SAME_DAY') DEFAULT 'NORMAL',
  work_type     ENUM('HANDWRITTEN','TYPED','PRINTED') DEFAULT 'HANDWRITTEN',
  status        ENUM('PENDING','ASSIGNED','IN_PROGRESS','COMPLETED','DELIVERED','CANCELLED') DEFAULT 'PENDING',
  total_cost    DECIMAL(10,2),
  material_cost DECIMAL(10,2) DEFAULT 0.00,
  writer_earning DECIMAL(10,2),
  commission     DECIMAL(10,2),
  file_urls      TEXT,
  completed_file_urls TEXT,
  notes          TEXT,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (student_id) REFERENCES users(id),
  FOREIGN KEY (writer_id)  REFERENCES users(id),
  FOREIGN KEY (college_id) REFERENCES colleges(id)
);