# Production specific configurations
spring.jpa.show-sql=false
logging.level.com.academix=INFO
logging.level.org.springframework.security=INFO

# Enforce secure DB connection defaults
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/academix?useSSL=true&serverTimezone=Asia/Kolkata}
